### PR TITLE
Dpdk bug fix

### PR DESCRIPTION
**Pull request by h4xhor**
Hi Iwan, there is still the performance issue with examples/dpdkNimExamples/rxtx_callbacks.

... but apart from that there should be no other bugs as far as I know.

### CODE REVIEW

**Comment by iwanbk** [comment]
```
If you installed using nimble (step 1) the bindings will be here

~/.nimble/pkgs/dpdk-0.1.0/src

Find a good directory to put src directory eg. ~/.nimble/pkgs/dpdk-0.1.0/src
Open makeDPDKNim.sh in a text editor. Please make changes to nim_src variable to indicate where is your above directory:
```
A proper nimble package shouldn't need these:
- user code to be placed under `~/.nimble` dir
- user code should able to import the package easily, without need to know the nimble package location

**Comment by iwanbk** [comment]
also, why we need long directory name like:
- dpdkNimInc
- dpdkNimExamples

why not simply:
- inc or include
- examples

because we already know that it is about `dpdk` and written in `nim`

**Comment by iwanbk** [comment]
FYI @nbabenko

**Comment by h4xhor** [comment]
Hi Iwan, 
User can now import "dpdk" directly without needing to know about package location. 

I've modified the makeDPDKNim.sh bash script to use whoami so no need to edit any paths here also.

I've shortened the directory names down. Let me know if there is any further changes required.

Thanks.

**Comment by iwanbk** [comment]
```
User can now import "dpdk" directly without needing to know about package location.
```
cool
```
I've modified the makeDPDKNim.sh bash script to use whoami so no need to edit any paths here also.
```
`/home/username` only works for non root user :)

```
I've shortened the directory names down.
```
thanks.

```
 Let me know if there is any further changes required.
```
if possible, only the `whoami` issue with root.

**Comment by iwanbk** [comment]
```
if possible, only the whoami issue with root.
```

what i meant, this line 
```
nim_src="/home/$(whoami)/.nimble/pkgs/dpdk-0.1.0/
```
It only works for non root user, because home directory of root is `/root/`, not `/home/root`

**Comment by iwanbk** [comment]
after looked more closely at `makeDPDKNim.sh`, some improvements that we can make:
- simply install *.a like `rteErrorWrapper` to `/usr/local/lib`
- move `c_compiler_options` etc.. to `nim.cfg` (see isa binding for example)

**Comment by h4xhor** [comment]
Hi Iwan,

makeDPDKNim.sh now has a check for root user, so it installs .nimble into /root/ for root user.
 19 # directory containing the DPDK Nim directories dpdkNimInc, rteErrorWrapper and extraCHdrs4Nim
 20 usr=$(whoami)
 21 if [ "root" == $usr ]; then                                                   
 22   nim_src="/root/.nimble/pkgs/dpdk-0.1.0/"                                    
 23 else
 24   nim_src="/home/$(whoami)/.nimble/pkgs/dpdk-0.1.0/"                          
 25 fi


instC_DPDK.sh now installs rte_error_wrapper.a into /usr/local/lib/
 76   echo "installing rte_error_wrapper.a"
 77   cmd="cp rteErrorWrapper/rte_error_wrapper.a /usr/local/lib/"
 78   echo -e "\n$cmd"; eval $cmd

uninstC_DPDK.sh now uninstalls /usr/local/lib/rte_error_wrapper.a
 30   echo "uninstalling rte_error_wrapper.a"
 31   cmd="rm /usr/local/lib/rte_error_wrapper.a"
 32   echo -e "\n$cmd"; eval $cmd

I have updated the README.md to have instructions for copying nim.cfg into the project directory. They still have to call makeDPDKNim.sh though.

dpdk.nimble now skips rte_error_wrapper.a
 16 # rteErrorWrapper/rte_error_wrapper.a installed by instC_DPDK.sh
 17 skipExt = @["a"]

**Comment by h4xhor** [comment]
Hi Iwan, I've updated the rte_error_wrapper.a (in rteErrorWrapper/) to now be librte_error_wrapper.a. 

I've updated the files nim.cfg, instC_DPDK.sh uninstC_DPDK.sh and dpdk.nimble to also use the new name.

**Comment by iwanbk** [comment]
@h4xhor 
thanks for the update.
i still got this error below when doing `nimble install`
```
installing librte_error_wrapper.a

cp rteErrorWrapper/librte_error_wrapper.a /usr/local/lib/
cp: cannot stat 'rteErrorWrapper/librte_error_wrapper.a': No such file or directory
```

**Comment by h4xhor** [comment]
@iwanbk I had forgotten to `cd ..` after the `cd dpdk-stable-16.07.2`. I added these lines to instC_DPDK.sh:
```
 64   cmd="cd .."
 65   echo -e "\n$cmd"; eval $cmd
```

so now it can now find `rteErrorWrapper/librte_error_wrapper.a`

**Comment by iwanbk** [comment]
@nbabenko OK for me, please merge if OK for you.

**Pull request merged**
